name = "GamersBuried"
author = "Gamers"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2342b45a4e9de98e5acd79282d03745f7b8355967a222addaa2782c24ae48f59"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
